name: EEGToText
channels:
  - pytorch
  - anaconda
  - dglteam
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.5.30=ha878542_0
  - catalogue=1.0.0=py38_1
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - conda=4.10.3=py38h578d9bd_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py38_0
  - cymem=2.0.5=py38h2531618_0
  - cython-blis=0.4.1=py38h7b6447c_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - dgl-cuda10.2=0.5.2=py38_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.0=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py38_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210216=h27cfd23_1
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - murmurhash=1.0.5=py38h2531618_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.5=py_0
  - ninja=1.10.2=hff7bd54_1
  - nltk=3.5=py_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h7f98852_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.0.1=py38h06a4308_0
  - plac=0.9.6=py38_1
  - preshed=3.0.5=py38h2531618_4
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pycurl=7.43.0.6=py38h1ba5d50_0
  - pymongo=3.11.2=py38h2531618_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - regex=2021.4.4=py38h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel.yaml=0.17.10=py38h497a2fe_0
  - ruamel.yaml.clib=0.2.2=py38h497a2fe_2
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scikit-learn=0.23.2=py38h0573a6f_0
  - scipy=1.6.2=py38h91f5cce_0
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - spacy=2.3.2=py38hfd86e86_0
  - sqlite=3.36.0=hc218d9a_0
  - srsly=1.0.5=py38h2531618_0
  - thinc=7.4.1=py38hfd86e86_0
  - threadpoolctl=2.2.0=pyhbf3da8f_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py38
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.0=pyhd3eb1b0_1
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.11.0
    - alabaster==0.7.12
    - allennlp==2.6.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - apriltag==0.0.16
    - argon2-cffi==20.1.0
    - argparse==1.4.0
    - arrow==1.0.1
    - astunparse==1.6.3
    - babel==2.9.0
    - backcall==0.2.0
    - backports-csv==1.0.7
    - beautifulsoup4==4.9.3
    - bibtexparser==1.2.0
    - black==21.4b2
    - bleach==4.0.0
    - blobfile==1.1.1
    - boto3==1.18.21
    - botocore==1.21.21
    - cachetools==4.1.1
    - catalyst==20.11
    - cfgv==3.2.0
    - charset-normalizer==2.0.4
    - checklist==0.0.11
    - cheroot==8.5.2
    - cherrypy==18.6.1
    - cloudpickle==1.6.0
    - configparser==5.0.2
    - coverage==3.7.1
    - coveralls==1.1
    - cssselect==1.1.0
    - cython==0.29.21
    - dall-e==0.1
    - dataclasses==0.6
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - detectron2==0.5+cu111
    - dill==0.3.4
    - distlib==0.3.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.16
    - dominate==2.6.0
    - efficientnet-pytorch==0.6.3
    - en-core-web-lg==2.3.1
    - en-core-web-sm==2.3.1
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - extratools==0.8.2.1
    - fake-useragent==0.1.11
    - feedfinder2==0.0.4
    - feedparser==6.0.8
    - filelock==3.0.12
    - filetype==1.0.7
    - flask==1.1.2
    - free-proxy==1.0.2
    - ftfy==6.0.3
    - future==0.18.2
    - fuzzy-match==0.0.1
    - fvcore==0.1.5.post20210812
    - gast==0.3.3
    - gensim==4.0.1
    - gingerit==0.8.2
    - gitdb==4.0.5
    - gitpython==3.1.11
    - gmatch4py==0.2.5b0
    - google-api-core==1.31.1
    - google-api-python-client==2.19.1
    - google-auth==1.34.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.2
    - google-cloud-core==1.7.2
    - google-cloud-storage==1.41.1
    - google-crc32c==1.1.2
    - google-pasta==0.2.0
    - google-resumable-media==1.3.3
    - googleapis-common-protos==1.53.0
    - googlesearch-python==1.0.1
    - grpcio==1.33.2
    - gspan-mining==0.2.3
    - h5py==2.10.0
    - html2text==2020.1.16
    - httplib2==0.19.1
    - huggingface-hub==0.0.8
    - hydra-core==1.1.0
    - identify==1.5.14
    - imageio==2.9.0
    - imagesize==1.2.0
    - importlib-resources==5.2.2
    - iniconfig==1.1.1
    - iopath==0.1.8
    - ipykernel==5.5.0
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - iso-639==0.4.5
    - itsdangerous==1.1.0
    - jaraco-classes==3.2.1
    - jaraco-collections==3.4.0
    - jaraco-functools==3.3.0
    - jaraco-text==3.5.1
    - jedi==0.17.2
    - jieba==0.42.1
    - jieba3k==0.35.1
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonnet==0.17.0
    - jsonpatch==1.28
    - jsonpointer==2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - langdetect==1.0.7
    - language-tool-python==2.5.5
    - latexcodec==2.0.1
    - lmdb==1.1.1
    - lxml==4.6.2
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mne==0.23.0
    - more-itertools==8.8.0
    - munch==2.5.0
    - munkres==1.1.4
    - mwclient==0.10.1
    - mypy==0.812
    - mypy-extensions==0.4.3
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - newspaper3k==0.2.8
    - nibabel==3.2.1
    - nodeenv==1.5.0
    - notebook==6.4.3
    - oauthlib==3.1.0
    - omegaconf==2.1.0
    - opencv-python==4.5.1.48
    - openpyxl==3.0.7
    - opt-einsum==3.3.0
    - overrides==3.1.0
    - packaging==20.7
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pathspec==0.8.1
    - pathtools==0.1.2
    - patternfork-nosql==3.6
    - pdfminer-six==20201018
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plotly==4.13.0
    - pluggy==0.13.1
    - portalocker==2.3.0
    - portend==2.7.1
    - pre-commit==2.10.1
    - prefixspan==0.5.2
    - pretrainedmodels==0.7.4
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybtex==0.22.2
    - pycocotools==2.0.2
    - pycryptodomex==3.10.1
    - pydot==1.4.1
    - pygments==2.7.2
    - pytest==6.2.2
    - pytest-cov==2.5.1
    - python-docx==0.8.11
    - python-dotenv==0.15.0
    - python-graphviz==0.16
    - python-levenshtein==0.12.2
    - python-slugify==4.0.1
    - pytz==2020.4
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - rebiber==1.1.2
    - requests-file==1.5.1
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rouge==1.0.0
    - rsa==4.6
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.5.0
    - sacremoses==0.0.45
    - scholarly==1.1.0
    - scikit-image==0.17.2
    - seaborn==0.11.1
    - segmentation-models-pytorch==0.1.2
    - selenium==3.141.0
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - sentry-sdk==1.3.1
    - sgmllib3k==1.0.0
    - shortuuid==1.0.1
    - simpleitk==2.0.2
    - sklearn==0.0
    - smart-open==3.0.0
    - smmap==3.0.4
    - snowballstemmer==2.1.0
    - sortedcontainers==2.3.0
    - soupsieve==2.0.1
    - spacy-langdetect==0.1.2
    - sphinx==3.5.1
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - stem==1.8.0
    - stop-words==2018.7.23
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tempora==4.1.1
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.1
    - termcolor==1.1.0
    - terminado==0.11.0
    - testpath==0.5.0
    - texsoup==0.1.4
    - text-unidecode==1.3
    - thop==0.0.31-2005241907
    - tifffile==2020.11.26
    - timm==0.1.20
    - tinysegmenter==0.3
    - tldextract==3.1.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - toolz==0.11.1
    - torch==1.7.0
    - torchfile==0.1.0
    - torchnet==0.0.4
    - torchsummary==1.5.1
    - torchsummaryx==1.3.0
    - torchvision==0.8.1
    - traitlets==5.0.5
    - transformers==4.6.1
    - typed-ast==1.4.2
    - unidecode==1.2.0
    - uritemplate==3.0.1
    - virtualenv==20.4.2
    - visdom==0.1.8.9
    - wandb==0.11.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wget==3.2
    - widgetsnbextension==3.5.1
    - wikipedia==1.4.0
    - wikitextparser==0.47.5
    - wptools==0.4.17
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - yacs==0.1.8
    - zc-lockfile==2.0
prefix: /shared/nas/data/m1/wangz3/miniconda
